export const SelectIcons = {
  CaretDown:
    'data:image/ico;base64,AAABAAEACQkCAAEAAQB4AAAAFgAAACgAAAAJAAAAEgAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAD/gAAA/4AAAO+AAADHgAAAg4AAAAGAAAD/gAAA/4AAAA==',
}
