export type WindowMenuItemIconType = 'check' | 'circle'

export type WindowMenuItemIcon = {
  dataUri: string
  top: number
  left: number
}

export const WindowMenuItemIcons: Record<WindowMenuItemIconType, WindowMenuItemIcon> = {
  check: {
    dataUri:
      'data:image/ico;base64,AAABAAIABwcCAAEAAQBoAAAAJgAAAAcHAgABAAEAaAAAAI4AAAAoAAAABwAAAA4AAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3gAAAI4AAAAGAAAAIgAAAHAAAAD4AAAA/AAAACgAAAAHAAAADgAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA',
    top: 6,
    left: 5,
  },
  circle: {
    dataUri:
      'data:image/ico;base64,AAABAAIABgYCAAEAAQBgAAAAJgAAAAYGAgABAAEAYAAAAIYAAAAoAAAABgAAAAwAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAoAAAABgAAAAwAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAA=',
    top: 5,
    left: 6,
  },
}
