export type WindowMenuItemIconType = 'check' | 'circle' | 'caretRight'

export type WindowMenuItemIcon = {
  dataUri: string
  top: number
  left: number
  simple?: boolean
}

export const WindowMenuItemIcons: Record<WindowMenuItemIconType, WindowMenuItemIcon> = {
  check: {
    dataUri:
      'data:image/ico;base64,AAABAAIABwcCAAEAAQBoAAAAJgAAAAcHAgABAAEAaAAAAI4AAAAoAAAABwAAAA4AAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3gAAAI4AAAAGAAAAIgAAAHAAAAD4AAAA/AAAACgAAAAHAAAADgAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA',
    top: 6,
    left: 5,
    simple: true,
  },
  circle: {
    dataUri:
      'data:image/ico;base64,AAABAAIABgYCAAEAAQBgAAAAJgAAAAYGAgABAAEAYAAAAIYAAAAoAAAABgAAAAwAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEAAAAAAAAAAAAAAAAAAAAAAAAAIQAAAAoAAAABgAAAAwAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAA/AAAAPwAAAD8AAAA/AAAAPwAAAA=',
    top: 5,
    left: 6,
    simple: true,
  },
  caretRight: {
    dataUri:
      'data:image/ico;base64,AAABAAIABwcCAAEAAQBoAAAAJgAAAAcHAgABAAEAaAAAAI4AAAAoAAAABwAAAA4AAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgAAAD4AAAAeAAAADgAAAB4AAAA+AAAAfgAAACgAAAAHAAAADgAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAAP4AAAD+AAAA/gAAAP4AAAD+AAAA',
    top: 4,
    left: 8,
    simple: true,
  },
}
